version: '3.8'

services:
  ecoa-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ecoa-ecommerce-app
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    restart: unless-stopped

